# generated by datamodel-codegen:
#   filename:  colibri_schema.json
#   timestamp: 2026-08-06T03:34:50+00:00

from __future__ import annotations

from pydantic import BaseModel


class Node(BaseModel):
    id: str
    label: str
    file_type: str
    source_file: str | None = None
    source_location: str | None = None
    source_url: str | None = None
    captured_at: str | None = None
    author: str | None = None
    contributor: str | None = None
    rationale_for: str | None = None


class Edge(BaseModel):
    source: str
    target: str
    relation: str
    confidence: str
    confidence_score: float | None = None
    source_file: str | None = None
    source_location: str | None = None
    weight: float | None = None


class Hyperedge(BaseModel):
    id: str
    label: str
    nodes: list[str]
    relation: str
    confidence: str | None = None
    confidence_score: float | None = None
    source_file: str | None = None


class ColibriSchema(BaseModel):
    nodes: list[Node]
    edges: list[Edge]
    hyperedges: list[Hyperedge] | None = None
