# generated by datamodel-codegen:
#   filename:  graph_engine_schema.json
#   timestamp: 2026-08-07T04:04:33+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel


class ExecutionMode(Enum):
    dag = "dag"
    sequential = "sequential"
    parallel = "parallel"


class Status(Enum):
    pending = "pending"
    running = "running"
    completed = "completed"
    failed = "failed"


class NodeType(Enum):
    task = "task"
    subagent = "subagent"
    evaluator = "evaluator"
    remediation = "remediation"


class Status1(Enum):
    pending = "pending"
    running = "running"
    passed = "passed"
    completed = "completed"
    failed = "failed"
    skipped = "skipped"
    pending_subagent_dispatch = "pending_subagent_dispatch"


class Node(BaseModel):
    id: str
    node_type: NodeType
    status: Status1
    dependencies: list[str] | None = None
    subagent_role: str | None = None
    task_action: str | None = None
    error_message: str | None = None


class GraphEngineSchema(BaseModel):
    graph_id: str
    execution_mode: ExecutionMode
    status: Status
    remediation_count: int | None = 0
    max_remediations: int | None = 3
    nodes: list[Node]


class EventType(Enum):
    WORKFLOW_STARTED = "WORKFLOW_STARTED"
    WORKFLOW_COMPLETED = "WORKFLOW_COMPLETED"
    WORKFLOW_FAILED = "WORKFLOW_FAILED"
    NODE_STARTED = "NODE_STARTED"
    NODE_COMPLETED = "NODE_COMPLETED"
    NODE_FAILED = "NODE_FAILED"
    NODE_SKIPPED = "NODE_SKIPPED"
    NODE_PENDING_SUBAGENT = "NODE_PENDING_SUBAGENT"
    REMEDIATION_TRIGGERED = "REMEDIATION_TRIGGERED"


class SymphonyEvent(BaseModel):
    event_id: str
    event_type: EventType
    timestamp: str
    graph_id: str
    node_id: str | None = None
    payload: dict[str, Any] | None = None
    error_message: str | None = None


class SymphonyNodeSpec(BaseModel):
    id: str
    node_type: NodeType
    role: str | None = None
    instructions: str | None = None
    dependencies: list[str] | None = None


class SymphonyWorkflowSpec(BaseModel):
    name: str
    version: str | None = "1.0.0"
    description: str | None = None
    execution_mode: ExecutionMode | None = "dag"
    max_remediations: int | None = 3
    nodes: list[SymphonyNodeSpec]
