# generated by datamodel-codegen:
#   filename:  graph_schema.json
#   timestamp: 2026-08-07T04:04:33+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel


class Node(BaseModel):
    id: str
    label: str
    type: str


class Edge(BaseModel):
    source: str
    target: str
    type: str
    weight: float | None = None


class GraphData(BaseModel):
    nodes: list[Node]
    edges: list[Edge]
    metadata: dict[str, Any]
