# generated by datamodel-codegen:
#   filename:  graph_schema.json
#   timestamp: 2026-08-06T03:34:50+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel


class Node(BaseModel):
    id: str
    label: str
    type: str
    source_file: str | None = None


class Edge(BaseModel):
    source: str
    target: str
    type: str
    weight: float | None = None
    confidence: str | None = "EXTRACTED"
    confidence_score: float | None = 1.0


class GraphData(BaseModel):
    nodes: list[Node]
    edges: list[Edge]
    metadata: dict[str, Any]
