# generated by datamodel-codegen:
#   filename:  okf_schema.json
#   timestamp: 2026-08-07T04:04:33+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field, constr


class Type(Enum):
    report = "report"
    guide = "guide"
    architecture = "architecture"
    spec = "spec"
    api = "api"
    benchmark = "benchmark"
    policy = "policy"
    reference = "reference"
    lesson = "lesson"


class Status(Enum):
    draft = "draft"
    review = "review"
    approved = "approved"
    deprecated = "deprecated"


class OKFFrontmatter(BaseModel):
    title: str = Field(..., description="Document title")
    doc_id: constr(pattern=r"^okf-[a-z0-9-]+$") = Field(
        ..., description="Unique OKF document identifier"
    )
    version: constr(pattern=r"^\d+\.\d+\.\d+$") = Field(
        ..., description="Semantic versioning string"
    )
    type: Type = Field(..., description="Document category type")
    status: Status | None = "approved"
    author: str | None = Field(None, description="Author or originating subsystem")
    created_at: str | None = Field(None, description="Creation timestamp in ISO-8601 format")
    updated_at: str | None = Field(None, description="Last updated timestamp in ISO-8601 format")
    tags: list[str] | None = Field(None, description="Metadata search tags")
