# generated by datamodel-codegen:
#   filename:  orchestration_schema.json
#   timestamp: 2026-07-29T21:37:11+00:00

from __future__ import annotations

from pydantic import BaseModel


class Agent(BaseModel):
    role: str
    status: str
    subtasks: list[str] | None = None


class OrchestrationPlan(BaseModel):
    task: str
    project: str
    agents: list[Agent]
    execution_mode: str | None = None
