# generated by datamodel-codegen:
#   filename:  plugin_schema.json
#   timestamp: 2026-08-06T03:34:50+00:00

from __future__ import annotations

from pydantic import BaseModel


class Entrypoints(BaseModel):
    graph_engine: str | None = None
    skillopt: str | None = None
    orchestration: str | None = None


class PluginSchema(BaseModel):
    name: str
    version: str
    description: str
    author: str | None = None
    entrypoints: Entrypoints
    skills: list[str] | None = None
