# generated by datamodel-codegen:
#   filename:  verification_schema.json
#   timestamp: 2026-08-07T04:04:33+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel


class Decision(Enum):
    allow = "allow"
    deny = "deny"


class VerificationResult(BaseModel):
    decision: Decision
    reason: str | None = None
    additionalContext: str | None = None
